// topics.js — static content data for all topics.
// Each topic has up to 12 pairs; difficulty determines how many are used.
// A pair links a `term` card to a `def` (short use/meaning) card, and carries
// a `learn` explanation shown in the Match Found modal.

export const topics = {
  dataBasics: {
    id: 'dataBasics',
    title: 'Data Science Basics Match',
    description: 'Match basic data science concepts',
    icon: 'database',
    color: 'blue',
    pairs: [
      { term: { label: 'Data', icon: 'hash' }, def: { label: 'Raw facts & figures', icon: 'file-text' }, learn: 'Data represents raw facts and figures that have not yet been processed.', example: 'A spreadsheet with thousands of unsorted customer ages.', tip: 'Think of "Data" as the raw ingredients before baking a cake.' },
      { term: { label: 'Information', icon: 'lightbulb' }, def: { label: 'Processed data', icon: 'puzzle' }, learn: 'Information is data that has been processed and organized to be meaningful.', example: 'A chart showing that the average customer age is 34.', tip: 'Information is what informs your decisions.' },
      { term: { label: 'Dataset', icon: 'folder' }, def: { label: 'Collection of data', icon: 'package' }, learn: 'A dataset is an organized collection of related data, usually in tabular form.', example: 'The famous Titanic passenger list used in ML tutorials.', tip: 'A "set" of "data", just like a set of cards.' },
      { term: { label: 'Variable', icon: 'ruler' }, def: { label: 'Measurable characteristic', icon: 'target' }, learn: 'A variable is any characteristic, number, or quantity that can be measured or counted.', example: 'Height, weight, or income of a person.', tip: 'It\'s called a variable because its value can "vary".' },
      { term: { label: 'Feature', icon: 'dna' }, def: { label: 'Input column', icon: 'inbox' }, learn: 'A feature is an individual measurable input a model uses to make predictions.', example: 'Square footage of a house used to predict its price.', tip: 'Features are the "clues" a model uses.' },
      { term: { label: 'Label', icon: 'tag' }, def: { label: 'Target value', icon: 'target' }, learn: 'A label is the known output or answer a model is trained to predict.', example: 'Whether an email is "Spam" or "Not Spam".', tip: 'The label is the "answer key".' },
      { term: { label: 'Model', icon: 'bot' }, def: { label: 'Learned pattern', icon: 'brain' }, learn: 'A model is a mathematical representation trained to find patterns and make predictions.', example: 'A recommendation engine suggesting movies on Netflix.', tip: 'A model is like a digital brain trained on past experience.' },
      { term: { label: 'Algorithm', icon: 'settings' }, def: { label: 'Step-by-step rules', icon: 'clipboard-list' }, learn: 'An algorithm is a defined set of steps used to solve a problem or train a model.', example: 'Linear regression or Random Forest.', tip: 'An algorithm is the "recipe" the computer follows.' },
      { term: { label: 'Big Data', icon: 'server' }, def: { label: 'Massive datasets', icon: 'waves' }, learn: 'Big Data refers to datasets too large or complex for traditional tools to process.', example: 'Petabytes of user clickstreams generated by Amazon every day.', tip: 'Remember the 3 Vs: Volume, Velocity, Variety.' },
      { term: { label: 'Structured Data', icon: 'blocks' }, def: { label: 'Rows and columns', icon: 'bar-chart' }, learn: 'Structured data is organized neatly into rows and columns, like a spreadsheet.', example: 'A SQL database of employee records.', tip: 'Structured means it fits perfectly into a table.' },
      { term: { label: 'Unstructured Data', icon: 'hurricane' }, def: { label: 'Text, images, audio', icon: 'image' }, learn: 'Unstructured data has no fixed format, such as text, images, or audio files.', example: 'Thousands of customer reviews written in natural language.', tip: 'Unstructured is messy, like a pile of photos.' },
      { term: { label: 'Metadata', icon: 'info' }, def: { label: 'Data about data', icon: 'bookmark' }, learn: 'Metadata is descriptive information that explains the context of other data.', example: 'The location, date, and camera settings saved inside a JPEG photo file.', tip: '"Meta" means about itself. Data about data.' },
    ],
  },

  pythonLibraries: {
    id: 'pythonLibraries',
    title: 'Python Library Match',
    description: 'Match Python libraries with their uses',
    icon: 'file-code-2',
    color: 'green',
    pairs: [
      { term: { label: 'Pandas', icon: 'table' }, def: { label: 'Data analysis', icon: 'search' }, learn: 'Pandas is a Python library used for data manipulation and analysis.', example: 'An analyst uses Pandas to quickly filter 10,000 rows of sales data to find only the transactions from last December.' },
      { term: { label: 'NumPy', icon: 'hash' }, def: { label: 'Numerical computing', icon: 'calculator' }, learn: 'NumPy is used for numerical computing and working with arrays.', example: 'A scientist uses NumPy to perform complex mathematical operations on a 3D grid of climate temperatures.' },
      { term: { label: 'Matplotlib', icon: 'line-chart' }, def: { label: 'Data visualization', icon: 'palette' }, learn: 'Matplotlib is used to create charts and data visualizations.', example: 'A researcher uses Matplotlib to generate a line chart showing company revenue growth over the past 5 years.' },
      { term: { label: 'Scikit-learn', icon: 'bot' }, def: { label: 'Machine learning', icon: 'brain' }, learn: 'Scikit-learn provides simple, efficient tools for machine learning in Python.', example: 'A developer uses Scikit-learn to train a random forest model that predicts if a bank transaction is fraudulent.' },
      { term: { label: 'Seaborn', icon: 'waves' }, def: { label: 'Statistical plots', icon: 'bar-chart' }, learn: 'Seaborn builds on Matplotlib to create attractive statistical graphics.', example: 'A statistician uses Seaborn to create a heatmap that clearly highlights the correlation between housing prices and square footage.' },
      { term: { label: 'TensorFlow', icon: 'hexagon' }, def: { label: 'Deep learning', icon: 'network' }, learn: 'TensorFlow is an open-source framework for building deep learning models.', example: 'A tech company uses TensorFlow to train a massive deep neural network that recognizes objects in autonomous vehicles.' },
      { term: { label: 'PyTorch', icon: 'flame' }, def: { label: 'Neural networks', icon: 'brain' }, learn: 'PyTorch is a flexible deep learning framework popular for neural networks.', example: 'AI researchers use PyTorch to quickly prototype and experiment with a new natural language processing model.' },
      { term: { label: 'SciPy', icon: 'test-tube' }, def: { label: 'Scientific computing', icon: 'microscope' }, learn: 'SciPy provides tools for scientific and technical computing tasks.', example: 'An engineer uses SciPy to process and filter out background noise from an audio signal.' },
      { term: { label: 'Keras', icon: 'sliders' }, def: { label: 'High-level deep learning', icon: 'zap' }, learn: 'Keras offers a simple, high-level API for building neural networks.', example: 'A student uses Keras to quickly build their very first image classification model in just 10 lines of code.' },
      { term: { label: 'Plotly', icon: 'mouse-pointer-2' }, def: { label: 'Interactive charts', icon: 'trending-down' }, learn: 'Plotly is used to build interactive, web-ready charts and dashboards.', example: 'A data team builds a Plotly dashboard where executives can hover over sales charts to see exact daily numbers.' },
      { term: { label: 'Statsmodels', icon: 'ruler' }, def: { label: 'Statistical modeling', icon: 'ruler' }, learn: 'Statsmodels provides classes and functions for statistical model estimation.', example: 'An economist uses Statsmodels to run a robust linear regression to test if interest rates impact consumer spending.' },
      { term: { label: 'NLTK', icon: 'file-text' }, def: { label: 'Text processing', icon: 'type' }, learn: 'NLTK is a toolkit for working with human language and text data.', example: 'A marketer uses NLTK to tokenize and count the most frequently used adjectives in 5,000 product reviews.' },
    ],
  },

  workflow: {
    id: 'workflow',
    title: 'Data Science Workflow Match',
    description: 'Match steps in the data science process',
    icon: 'refresh-cw',
    color: 'purple',
    pairs: [
      { term: { label: 'Data Collection', icon: 'inbox' }, def: { label: 'Gather data', icon: 'globe' }, learn: 'Data collection is the process of gathering relevant information from various sources.', example: 'A supermarket collects customer purchase data to understand which products sell the most.' },
      { term: { label: 'Data Cleaning', icon: 'brush' }, def: { label: 'Remove errors', icon: 'x' }, learn: 'Data cleaning fixes or removes incorrect, incomplete, or duplicate data.', example: 'An analyst removes duplicate email addresses from a mailing list before sending a newsletter.' },
      { term: { label: 'Data Analysis', icon: 'search' }, def: { label: 'Find patterns', icon: 'puzzle' }, learn: 'Data analysis examines datasets to uncover trends and useful patterns.', example: 'A marketing team analyzes past ad campaigns to see which one generated the most clicks.' },
      { term: { label: 'Data Visualization', icon: 'bar-chart-2' }, def: { label: 'Present insights', icon: 'sparkles' }, learn: 'Data visualization presents findings visually so insights are easy to understand.', example: 'A dashboard showing real-time website traffic using colorful line charts and gauges.' },
      { term: { label: 'Feature Engineering', icon: 'hammer' }, def: { label: 'Create useful inputs', icon: 'dna' }, learn: 'Feature engineering transforms raw data into inputs that improve model performance.', example: 'Calculating a customer\'s "Account Age" by subtracting their join date from today\'s date.' },
      { term: { label: 'Model Training', icon: 'dumbbell' }, def: { label: 'Learn from data', icon: 'book' }, learn: 'Model training teaches an algorithm to recognize patterns using historical data.', example: 'Feeding 10,000 pictures of cats and dogs into a neural network so it learns the difference.' },
      { term: { label: 'Model Evaluation', icon: 'ruler' }, def: { label: 'Measure performance', icon: 'check-circle' }, learn: 'Model evaluation checks how accurately a trained model performs on new data.', example: 'Testing a spam filter on 1,000 new emails to see what percentage it correctly flags as spam.' },
      { term: { label: 'Model Deployment', icon: 'rocket' }, def: { label: 'Put into production', icon: 'globe' }, learn: 'Model deployment makes a trained model available for real-world use.', example: 'Integrating a recommendation engine into a live streaming app so users see personalized movie suggestions.' },
      { term: { label: 'Data Exploration', icon: 'compass' }, def: { label: 'Understand the data', icon: 'microscope' }, learn: 'Data exploration is the first look at a dataset to understand its structure.', example: 'A data scientist quickly generates histograms of all numerical columns to see how the data is distributed.' },
      { term: { label: 'Data Preprocessing', icon: 'eraser' }, def: { label: 'Prepare raw data', icon: 'package' }, learn: 'Data preprocessing transforms raw data into a clean, usable format.', example: 'Converting all text in a dataset to lowercase and removing punctuation before sentiment analysis.' },
      { term: { label: 'Hypothesis Testing', icon: 'test-tube' }, def: { label: 'Validate assumptions', icon: 'ruler' }, learn: 'Hypothesis testing uses statistics to check whether an assumption about data holds true.', example: 'Running an A/B test to see if a red "Buy Now" button gets statistically more clicks than a blue one.' },
      { term: { label: 'Reporting', icon: 'file-text' }, def: { label: 'Share results', icon: 'megaphone' }, learn: 'Reporting communicates data findings clearly to stakeholders and decision makers.', example: 'Presenting a monthly slide deck to the CEO showing how active users grew by 15%.' },
    ],
  },

  statistics: {
    id: 'statistics',
    title: 'Statistics Match',
    description: 'Match statistical terms with meanings',
    icon: 'bar-chart',
    color: 'coral',
    pairs: [
      { term: { label: 'Mean', icon: 'divide' }, def: { label: 'Average', icon: 'calculator' }, learn: 'Mean is the average value of a set of numbers.', example: 'Adding up the ages of 10 people and dividing by 10 to find the mean age.' },
      { term: { label: 'Median', icon: 'target' }, def: { label: 'Middle value', icon: 'map-pin' }, learn: 'Median is the middle value in a dataset when values are sorted in order.', example: 'Finding the exact middle salary in a company to avoid being skewed by the CEO\'s extreme pay.' },
      { term: { label: 'Mode', icon: 'repeat' }, def: { label: 'Most frequent value', icon: 'hash' }, learn: 'Mode is the value that occurs most often in a dataset.', example: 'A shoe store stocks up on size 9 because it is the mode (most common size) sold.' },
      { term: { label: 'Standard Deviation', icon: 'ruler' }, def: { label: 'Data spread', icon: 'wind' }, learn: 'Standard deviation measures how spread out values are from the mean.', example: 'If a class\'s test scores have a low standard deviation, it means most students scored very close to the class average.' },
      { term: { label: 'Variance', icon: 'maximize' }, def: { label: 'Squared spread', icon: 'square' }, learn: 'Variance measures how far data points spread out from their average value.', example: 'An investor calculates the variance of a stock\'s daily returns to understand its volatility and risk.' },
      { term: { label: 'Correlation', icon: 'link' }, def: { label: 'Relationship strength', icon: 'handshake' }, learn: 'Correlation measures how strongly two variables move together.', example: 'Discovering a high positive correlation between ice cream sales and sunscreen sales during the summer.' },
      { term: { label: 'Regression', icon: 'trending-down' }, def: { label: 'Predict a value', icon: 'eye' }, learn: 'Regression is a technique used to predict a continuous numeric value.', example: 'Using linear regression to predict a house\'s selling price based on its square footage and number of bedrooms.' },
      { term: { label: 'Probability', icon: 'dices' }, def: { label: 'Chance of an event', icon: 'leaf' }, learn: 'Probability measures how likely an event is to occur.', example: 'A weather app calculating a 75% probability of rain tomorrow based on historical cloud patterns.' },
      { term: { label: 'Outlier', icon: 'alert-circle' }, def: { label: 'Unusual data point', icon: 'alert-triangle' }, learn: 'An outlier is a data point that differs significantly from the rest of the data.', example: 'A single $1,000,000 transaction in a dataset where all other purchases are under $100.' },
      { term: { label: 'Percentile', icon: 'bar-chart-horizontal' }, def: { label: 'Relative position', icon: 'bar-chart' }, learn: 'A percentile shows the relative standing of a value within a dataset.', example: 'Scoring in the 90th percentile on a test means you scored better than 90% of the people who took it.' },
      { term: { label: 'Normal Distribution', icon: 'bell' }, def: { label: 'Bell curve shape', icon: 'bell' }, learn: 'A normal distribution is a symmetric, bell-shaped spread of data around the mean.', example: 'Plotting the heights of adult men in a city, where most are average height and very few are extremely tall or short.' },
      { term: { label: 'Hypothesis', icon: 'brain' }, def: { label: 'Testable claim', icon: 'file-text' }, learn: 'A hypothesis is a testable statement about the relationship between variables.', example: 'A scientist proposes the hypothesis that "plants given more sunlight will grow 20% faster."' },
    ],
  },

  careers: {
    id: 'careers',
    title: 'Data Science Career Match',
    description: 'Match jobs with their responsibilities',
    icon: 'briefcase',
    color: 'yellow',
    pairs: [
      { term: { label: 'Data Analyst', icon: 'bar-chart' }, def: { label: 'Analyze reports', icon: 'trending-up' }, learn: 'A Data Analyst examines data and creates reports to support decisions.', example: 'A Data Analyst creates a weekly sales report to show which store branches are underperforming.' },
      { term: { label: 'Data Scientist', icon: 'microscope' }, def: { label: 'Build predictive models', icon: 'eye' }, learn: 'A Data Scientist builds predictive models to solve complex business problems.', example: 'A Data Scientist builds a machine learning model that predicts which customers are likely to cancel their subscriptions.' },
      { term: { label: 'Data Engineer', icon: 'wrench' }, def: { label: 'Manage data pipelines', icon: 'hammer' }, learn: 'A Data Engineer designs and manages the pipelines that move and store data.', example: 'A Data Engineer builds an automated pipeline that moves raw website click data into a secure data warehouse every night.' },
      { term: { label: 'ML Engineer', icon: 'bot' }, def: { label: 'Deploy ML models', icon: 'rocket' }, learn: 'An ML Engineer builds and deploys machine learning models into production.', example: 'An ML Engineer optimizes a recommendation model and deploys it so it can serve 10,000 users per second.' },
      { term: { label: 'Business Analyst', icon: 'pie-chart' }, def: { label: 'Bridge data & strategy', icon: 'git-merge' }, learn: 'A Business Analyst connects data insights with business strategy and goals.', example: 'A Business Analyst uses data to convince the marketing team to shift their budget from TV ads to social media.' },
      { term: { label: 'BI Developer', icon: 'monitor' }, def: { label: 'Build dashboards', icon: 'layout-dashboard' }, learn: 'A BI Developer creates dashboards and reports for business intelligence.', example: 'A BI Developer builds an interactive Tableau dashboard for the CEO to monitor global sales in real-time.' },
      { term: { label: 'Statistician', icon: 'calculator' }, def: { label: 'Apply statistical methods', icon: 'sigma' }, learn: 'A Statistician applies statistical theory to collect and interpret data.', example: 'A Statistician designs a clinical trial to ensure a new drug\'s effectiveness results are statistically significant.' },
      { term: { label: 'Research Scientist', icon: 'flask-conical' }, def: { label: 'Advance new methods', icon: 'test-tube' }, learn: 'A Research Scientist develops new algorithms and advances data science methods.', example: 'A Research Scientist at Google invents a more efficient neural network architecture for language translation.' },
      { term: { label: 'Data Architect', icon: 'building' }, def: { label: 'Design data systems', icon: 'map' }, learn: 'A Data Architect designs the blueprint for how data is stored and organized.', example: 'A Data Architect plans how a massive hospital system will securely store and access millions of patient records.' },
      { term: { label: 'AI Engineer', icon: 'brain' }, def: { label: 'Build AI systems', icon: 'zap' }, learn: 'An AI Engineer designs and builds systems powered by artificial intelligence.', example: 'An AI Engineer programs a customer service chatbot that can accurately answer complex support questions.' },
      { term: { label: 'Analytics Manager', icon: 'user' }, def: { label: 'Lead analytics teams', icon: 'users' }, learn: 'An Analytics Manager leads a team that turns data into business decisions.', example: 'An Analytics Manager oversees a team of 5 analysts, prioritizing their projects and presenting their findings to the board.' },
      { term: { label: 'Data Product Manager', icon: 'compass' }, def: { label: 'Guide data products', icon: 'folder' }, learn: 'A Data Product Manager guides the strategy and roadmap for data-driven products.', example: 'A Data Product Manager decides what new features should be added to a company\'s internal data dashboard.' },
    ],
  },
};

export const topicOrder = ['dataBasics', 'pythonLibraries', 'workflow', 'statistics', 'careers'];

export const DIFFICULTY_PAIRS = { easy: 4, medium: 8, hard: 12 };

/** Assign each pair a stable id derived from topic + index, and add ids to term/def cards */
export function getTopicPairs(topicId, difficulty) {
  const topic = topics[topicId];
  if (!topic) return [];
  const count = DIFFICULTY_PAIRS[difficulty] || DIFFICULTY_PAIRS.easy;
  return topic.pairs.slice(0, count).map((pair, index) => ({
    pairId: `${topicId}-${index}`,
    term: pair.term,
    def: pair.def,
    learn: pair.learn,
    example: pair.example,
    tip: pair.tip,
  }));
}
